export const FETCHED_DOCUMENTS = 'FETCHED_DOCUMENTS';
export const FETCHED_DOCUMENT = 'FETCHED_DOCUMENT';

export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT';

export const LINE_UPDATED = 'LINE_UPDATED';
export const ADD_LINE = 'ADD_LINE';