export const FETCHED_SHEETS = 'FETCHED_SHEETS';
export const FETCHED_SHEET = 'FETCHED_SHEET';

export const SHEET_CREATED = 'SHEET_CREATED';
export const SHEET_UPDATED = 'SHEET_UPDATED';
export const SHEET_DELETED = 'SHEET_DELETED';

export const UPDATE_EDITOR_STATE = 'UPDATE_EDITOR_STATE';
export const UPDATE_RESULTS = 'UPDATE_RESULTS';
export const UPDATE_EDITOR = 'UPDATE_EDITOR';

export const WRITE_EDITOR = 'WRITE_EDITOR';
export const WRITE_RESULTS = 'WRITE_RESULTS';

export const TOGGLE_DEBUG = 'TOGGLE_DEBUG';
export const CATCH_ERROR = 'CATCH_ERROR';
