export const FETCHED_DOCUMENTS = 'FETCHED_DOCUMENTS';
export const FETCHED_DOCUMENT = 'FETCHED_DOCUMENT';

export const DOCUMENT_CREATED = 'DOCUMENT_CREATED';
export const DOCUMENT_UPDATED = 'DOCUMENT_UPDATED';
export const DOCUMENT_DELETED = 'DOCUMENT_DELETED';

export const LINE_UPDATED = 'LINE_UPDATED';
export const LINE_CREATED = 'LINE_CREATED';
export const LINE_DELETED = 'LINE_DELETED';
export const LINE_SELECTED = 'LINE_SELECTED';

export const ADD_LINE = 'ADD_LINE';
export const SELECT_LINE = 'SELECT_LINE';
export const SELECT_LINE_RELATIVE = 'SELECT_LINE_RELATIVE';

export const TOGGLE_DEBUG = 'TOGGLE_DEBUG';